CREATE DATABASE BIBLIOTECA
GO
USE BIBLIOTECA
GO

/*CREA TABLA AUTORES*/
CREATE TABLE AUTORES(
ID_AUTOR INT PRIMARY KEY IDENTITY(1,1),
NOMBRE_AUTOR NVARCHAR(60),
NACIONALIDAD_AUTOR NVARCHAR(20),
);

/*CREA TABLA LIBROS*/
CREATE TABLE LIBROS(
ID_LIBRO INT PRIMARY KEY IDENTITY(1,1),
TITULO_LIBRO NVARCHAR(40),
EDITORIAL_LIBRO NVARCHAR(30),
AREA_LIBRO NVARCHAR(20),
);

/*CREA TABLA LIB_AUT*/
CREATE TABLE LIB_AUT(
ID_AUTOR INT REFERENCES AUTORES(ID_AUTOR),
ID_LIBRO INT REFERENCES LIBROS(ID_LIBRO),
);

/*CREA TABLA ESTUDIANTES*/
CREATE TABLE ESTUDIANTES(
ID_ESTUDIANTE INT PRIMARY KEY IDENTITY(1,1),
CEDULA_IDENTIDAD NVARCHAR(11) UNIQUE,
NOMBRE_ESTUDIANTE NVARCHAR(60),
EDAD_ESTUDIANTE INT,
DIRECCION_ESTUDIANTE NVARCHAR(80),
CARRERA_ESTUDIANTE NVARCHAR(60)
);

/*CREA TABLA PRESTADOS*/
CREATE TABLE PRESTADOS(
ID_PRESTADO INT PRIMARY KEY IDENTITY(1,1),
ID_ESTUDIANTE INT REFERENCES ESTUDIANTES(ID_ESTUDIANTE),
ID_LIBRO INT REFERENCES LIBROS(ID_LIBRO),
FECHA_PRESTAMO DATETIME,
FECHA_DEVOLUCION DATETIME,
DEVUELTO NVARCHAR(2)
);

/*INSERTO VALORES A LA TABLA AUTORES*/
INSERT INTO AUTORES VALUES('GOETHE','ALEMAN');

INSERT INTO AUTORES VALUES('MARQUÉS DE SADE','FRANCES');

INSERT INTO AUTORES VALUES('MIGUEL DE CERVANTES','ESPAÑOL');

INSERT INTO AUTORES VALUES('JANE AUSTEN','INGLES');

INSERT INTO AUTORES VALUES('MARY SHELLEY','PANAMEÑO');

INSERT INTO AUTORES VALUES('VICTOR HUGO','ESPAÑOL');

/*INSERTO VALORES A LA TABLA LIBROS*/
INSERT INTO LIBROS VALUES('DON QUIJOTE','EDITORIAL JUVENTUD','LITERATURA');

INSERT INTO LIBROS VALUES('FAUSTO','ALIANZA EDITORIAL','LITERATURA');

INSERT INTO LIBROS VALUES('JUSTINE DE SADE','TUSQUETS EDITORES','NOVELA');

INSERT INTO LIBROS VALUES('EMMA','ALIANZA EDITORIAL','FICCION');

INSERT INTO LIBROS VALUES('FRANKENTEIN','VALDEMAR','NOVELA EPISTOLAR');

INSERT INTO LIBROS VALUES('LOS MISERABLES','EDITORIAL PORRUA','TRAGEDIA');


SELECT * FROM AUTORES;

SELECT * FROM LIBROS;

/*INSERTO VALORES A LA TABLA LIB_AUT*/
INSERT INTO LIB_AUT VALUES('3','1');

INSERT INTO LIB_AUT VALUES('1','2');

INSERT INTO LIB_AUT VALUES('2','3');

INSERT INTO LIB_AUT VALUES('4','4');

INSERT INTO LIB_AUT VALUES('5','5');

INSERT INTO LIB_AUT VALUES('6','6');

INSERT INTO LIB_AUT VALUES('3','6');

SELECT * FROM LIB_AUT;

/*INSERTO VALORES A LA TABLA ESTUDIANTES*/
INSERT INTO ESTUDIANTES VALUES('2-0811-0125','SEBASTIAN JIMENEZ BOLAÑOS','21','GRECIA, SAN ROQUE','INGENIERIA EN SISTEMAS');

INSERT INTO ESTUDIANTES VALUES('2-0453-0954','MAIKOL QUIROS RODRIGUEZ','24','ALAJUELA','ADMINISTRACION DE EMPRESAS');

INSERT INTO ESTUDIANTES VALUES('2-0125-0695','ISAAC RODRIGUEZ RODRIGUEZ','22','POAS','INGENIERIA HIDROELECTRICA');

INSERT INTO ESTUDIANTES VALUES('2-0742-0132','KEVIN RODRIGUEZ GONZALES','18','GRECIA, TACARES','INGENIERIA EN SISTEMAS');

INSERT INTO ESTUDIANTES VALUES('1-0253-0152','JOSUE RODRIGURZ ARCE','16','SAN JOSE','ADMINISTRACION DE EMPRESAS');

INSERT INTO ESTUDIANTES VALUES('3-0558-0159','STEVEN CORRALES ALFARO','17','HEREDIA','INGENIERIA QUIMICA');

INSERT INTO ESTUDIANTES VALUES('1-0555-0555','KEYLOR GOMEZ RODRIGUEZ','19','SAN JOSE','ADMINISTRACION DE EMPRESAS');

INSERT INTO ESTUDIANTES VALUES('3-0444-0444','ALEJANDRO MOLINA GOMEZ','15','HEREDIA','INGENIERIA QUIMICA');

SELECT * FROM ESTUDIANTES;

/*INSERTO VALORES A LA TABLA PRESTADOS*/
INSERT INTO PRESTADOS VALUES('1','6',GETDATE(),2022/06/20,'NO');

INSERT INTO PRESTADOS VALUES('2','5',GETDATE(),2022/07/30,'NO');

INSERT INTO PRESTADOS VALUES('3','4',GETDATE(),2022/06/30,'SI');

INSERT INTO PRESTADOS VALUES('4','3',GETDATE(),2022/06/29,'NO');

INSERT INTO PRESTADOS VALUES('5','2',GETDATE(),2022/07/30,'NO');

INSERT INTO PRESTADOS VALUES('6','1',GETDATE(),2022/06/30,'SI');

SELECT * FROM PRESTADOS;

/* 1 */

SELECT * 
FROM AUTORES
WHERE ID_AUTOR > 1;

/* 2 */
SELECT NOMBRE_ESTUDIANTE AS 'NOMBRE DEL ESTUDIANTE', EDAD_ESTUDIANTE AS EDAD
FROM ESTUDIANTES;

/* 3 */
SELECT NOMBRE_ESTUDIANTE AS 'NOMBRE DEL ESTUDIANTE'
FROM ESTUDIANTES
WHERE CARRERA_ESTUDIANTE = 'INGENIERIA EN SISTEMAS';

/* 4 */

/*lista por el primer apellido*/
SELECT NOMBRE_ESTUDIANTE AS 'NOMBRE DEL ESTUDIANTE'
FROM ESTUDIANTES
WHERE NOMBRE_ESTUDIANTE LIKE '% J%';
/*lista por el segundo apellido*/
SELECT NOMBRE_ESTUDIANTE AS 'NOMBRE DEL ESTUDIANTE'
FROM ESTUDIANTES
WHERE NOMBRE_ESTUDIANTE LIKE '% % A%';

/* 5 */

SELECT AUTORES.NOMBRE_AUTOR AS 'NOMBRE DEL AUTOR'
FROM LIB_AUT,AUTORES,LIBROS
WHERE LIB_AUT.ID_AUTOR = AUTORES.ID_AUTOR
AND LIB_AUT.ID_LIBRO = LIBROS.ID_LIBRO
AND LIBROS.TITULO_LIBRO = 'DON QUIJOTE';

/* 6 */

SELECT NOMBRE_AUTOR AS 'NOMBRE DEL AUTOR'
FROM AUTORES
WHERE NACIONALIDAD_AUTOR = 'ESPAÑOL'
OR NACIONALIDAD_AUTOR = 'FRANCES';

/* 7 */

SELECT TITULO_LIBRO AS 'TITULO DEL LIBRO'
FROM LIBROS
WHERE AREA_LIBRO != 'LITERATURA';

/* 8 */

SELECT TITULO_LIBRO AS 'TITULO DEL LIBRO'
FROM PRESTADOS,LIBROS,ESTUDIANTES
WHERE PRESTADOS.ID_ESTUDIANTE = ESTUDIANTES.ID_ESTUDIANTE
AND PRESTADOS.ID_LIBRO = LIBROS.ID_LIBRO
AND ESTUDIANTES.NOMBRE_ESTUDIANTE = 'SEBASTIAN JIMENEZ BOLAÑOS';

/* 9 */

SELECT NOMBRE_ESTUDIANTE AS 'NOMBRE DEL STUDIANTE'
FROM ESTUDIANTES
WHERE EDAD_ESTUDIANTE < 18;

/* 10 */

SELECT ESTUDIANTES.NOMBRE_ESTUDIANTE AS 'NOMBRE DEL STUDIANTE'
FROM ESTUDIANTES,LIBROS,PRESTADOS
WHERE PRESTADOS.ID_ESTUDIANTE = ESTUDIANTES.ID_ESTUDIANTE
AND PRESTADOS.ID_LIBRO = LIBROS.ID_LIBRO;

/* 11 *//**/

SELECT TITULO_LIBRO 
FROM LIBROS
WHERE EDITORIAL_LIBRO = 'EDITORIAL JUVENTUD' 
OR EDITORIAL_LIBRO = 'EDITORIAL PORRUA';

/* 12 */

SELECT LIBROS.TITULO_LIBRO  AS 'TITULO DEL LIBRO'
FROM LIB_AUT,AUTORES,LIBROS
WHERE LIB_AUT.ID_AUTOR = AUTORES.ID_AUTOR
AND LIB_AUT.ID_LIBRO = LIBROS.ID_LIBRO
AND AUTORES.NOMBRE_AUTOR = 'MIGUEL DE CERVANTES';

/* 13 */

SELECT TITULO_LIBRO  AS 'TITULO DEL LIBRO'
FROM LIBROS,PRESTADOS
WHERE PRESTADOS.ID_LIBRO = LIBROS.ID_LIBRO
AND FECHA_DEVOLUCION = 2022/07/30;

/* 14 */

SELECT SUM(EDAD_ESTUDIANTE) AS 'TOTAL DE LA EDAD DE LOS ESTUDIANTES'
FROM ESTUDIANTES;

/* 15 */

DECLARE @PROMEDIO INT
SET @PROMEDIO = 
        (
           SELECT AVG(EDAD_ESTUDIANTE) 
           FROM ESTUDIANTES
        )
SELECT * 
FROM ESTUDIANTES
WHERE EDAD_ESTUDIANTE > @PROMEDIO;

/* 16 */

CREATE PROC  SP_MOSTRAR_LIBROS_POR_AUTOR
@NOMBRE_AUTOR NVARCHAR(60)
AS
BEGIN
	SELECT LIBROS.TITULO_LIBRO AS 'TITULO DEL LIBRO'	  
	FROM LIB_AUT,AUTORES,LIBROS
	WHERE LIB_AUT.ID_AUTOR = AUTORES.ID_AUTOR
	AND LIB_AUT.ID_LIBRO = LIBROS.ID_LIBRO
	AND AUTORES.NOMBRE_AUTOR = @NOMBRE_AUTOR
END


EXEC SP_MOSTRAR_LIBROS_POR_AUTOR 'MIGUEL DE CERVANTES';

/* 17 */

CREATE PROC SP_INSERTAR_ESTUDIANTES(
@CEDULA_IDENTIDAD NVARCHAR(11),
@NOMBRE_ESTUDIANTE NVARCHAR(60),
@EDAD_ESTUDIANTE INT,
@DIRECCION_ESTUDIANTE NVARCHAR(80),
@CARRERA_ESTUDIANTE NVARCHAR(60)
)
AS
BEGIN
	INSERT INTO ESTUDIANTES(CEDULA_IDENTIDAD,NOMBRE_ESTUDIANTE,EDAD_ESTUDIANTE,DIRECCION_ESTUDIANTE,CARRERA_ESTUDIANTE)
	VALUES(@CEDULA_IDENTIDAD,@NOMBRE_ESTUDIANTE,@EDAD_ESTUDIANTE,@DIRECCION_ESTUDIANTE,@CARRERA_ESTUDIANTE)
END


EXEC SP_INSERTAR_ESTUDIANTES '1-0777-0772','JUSTIN GOMEZ SANCHEZ','22','SAN PEDRO, SAN JOSE','INGENIERIA ELECTRICA';

SELECT * FROM ESTUDIANTES;

/* 18 */

CREATE PROC SP_EDITAR_LIBRO(
@ID_LIBRO INT,
@TITULO_LIBRO NVARCHAR(40),
@EDITORIAL_LIBRO NVARCHAR(30),
@AREA_LIBRO NVARCHAR(20)
)
AS
BEGIN
	UPDATE LIBROS
	SET TITULO_LIBRO = @TITULO_LIBRO,
	EDITORIAL_LIBRO = @EDITORIAL_LIBRO,
	AREA_LIBRO = @AREA_LIBRO
	WHERE ID_LIBRO = @ID_LIBRO
END


INSERT INTO LIBROS VALUES('PRUEBA','EDITORIAL PRUEBA','LITERATURA');

EXEC SP_EDITAR_LIBRO 7,'PRUEBA UPDATE','EDITORIAL UPDATE','NOVELA';

SELECT * FROM LIBROS;

/* 19 */

CREATE TRIGGER TR_LISTAR_ESTUDIANTES
ON ESTUDIANTES
FOR INSERT
AS
BEGIN
SELECT * FROM ESTUDIANTES
END

EXEC SP_INSERTAR_ESTUDIANTES '1-0224-0433','JUAN CARLOS RODRIGUEZ ARCE','18','SAN JOSE','INGENIERIA EN SISTEMAS';

/* 20 */

