CREATE DATABASE BIBLIOTECA
GO
USE BIBLIOTECA
GO

/*CREA TABLA AUTORES*/
CREATE TABLE AUTORES(
ID_AUTOR INT PRIMARY KEY IDENTITY(1,1),
NOMBRE_AUTOR NVARCHAR(60) NOT NULL,
NACIONALIDAD_AUTOR NVARCHAR(20) NOT NULL,
);

/*CREA TABLA LIBROS*/
CREATE TABLE LIBROS(
ID_LIBRO INT PRIMARY KEY IDENTITY(1,1),
TITULO_LIBRO NVARCHAR(40) NOT NULL,
EDITORIAL_LIBRO NVARCHAR(30) NOT NULL,
AREA_LIBRO NVARCHAR(20) NOT NULL,
);

/*CREA TABLA LIB_AUT*/
CREATE TABLE LIB_AUT(
ID_AUTOR INT REFERENCES AUTORES(ID_AUTOR),
ID_LIBRO INT REFERENCES LIBROS(ID_LIBRO),
);

/*CREA TABLA ESTUDIANTES*/
CREATE TABLE ESTUDIANTES(
ID_ESTUDIANTE INT PRIMARY KEY IDENTITY(1,1),
CEDULA_IDENTIDAD NVARCHAR(11) UNIQUE NOT NULL,
NOMBRE_ESTUDIANTE NVARCHAR(60) NOT NULL,
EDAD_ESTUDIANTE INT NOT NULL,
DIRECCION_ESTUDIANTE NVARCHAR(80) NOT NULL,
CARRERA_ESTUDIANTE NVARCHAR(60) NOT NULL
);

/*CREA TABLA PRESTADOS*/
CREATE TABLE PRESTADOS(
ID_PRESTADO INT PRIMARY KEY IDENTITY(1,1),
ID_ESTUDIANTE INT REFERENCES ESTUDIANTES(ID_ESTUDIANTE),
ID_LIBRO INT REFERENCES LIBROS(ID_LIBRO),
FECHA_PRESTAMO DATE NOT NULL,
FECHA_DEVOLUCION DATE NOT NULL,
DEVUELTO NVARCHAR(2) NOT NULL
);

/*INSERTO VALORES A LA TABLA AUTORES*/
INSERT INTO AUTORES VALUES('GOETHE','ALEMAN');

INSERT INTO AUTORES VALUES('MARQUÉS DE SADE','FRANCES');

INSERT INTO AUTORES VALUES('MIGUEL DE CERVANTES','ESPAÑOL');

INSERT INTO AUTORES VALUES('JANE AUSTEN','INGLES');

INSERT INTO AUTORES VALUES('MARY SHELLEY','PANAMEÑO');

INSERT INTO AUTORES VALUES('VICTOR HUGO','ESPAÑOL');

/*INSERTO VALORES A LA TABLA LIBROS*/
INSERT INTO LIBROS VALUES('DON QUIJOTE','EDITORIAL JUVENTUD','LITERATURA');

INSERT INTO LIBROS VALUES('FAUSTO','ALIANZA EDITORIAL','LITERATURA');

INSERT INTO LIBROS VALUES('JUSTINE DE SADE','TUSQUETS EDITORES','NOVELA');

INSERT INTO LIBROS VALUES('EMMA','ALIANZA EDITORIAL','FICCION');

INSERT INTO LIBROS VALUES('FRANKENTEIN','VALDEMAR','NOVELA EPISTOLAR');

INSERT INTO LIBROS VALUES('LOS MISERABLES','EDITORIAL PORRUA','TRAGEDIA');


SELECT * FROM AUTORES;

SELECT * FROM LIBROS;

/*INSERTO VALORES A LA TABLA LIB_AUT*/
INSERT INTO LIB_AUT VALUES('3','1');

INSERT INTO LIB_AUT VALUES('1','2');

INSERT INTO LIB_AUT VALUES('2','3');

INSERT INTO LIB_AUT VALUES('4','4');

INSERT INTO LIB_AUT VALUES('5','5');

INSERT INTO LIB_AUT VALUES('6','6');

INSERT INTO LIB_AUT VALUES('3','6');

SELECT * FROM LIB_AUT;

/*INSERTO VALORES A LA TABLA ESTUDIANTES*/
INSERT INTO ESTUDIANTES VALUES('2-0811-0125','SEBASTIAN JIMENEZ BOLAÑOS','21','GRECIA, SAN ROQUE','INGENIERIA EN SISTEMAS');

INSERT INTO ESTUDIANTES VALUES('2-0453-0954','MAIKOL QUIROS RODRIGUEZ','24','ALAJUELA','ADMINISTRACION DE EMPRESAS');

INSERT INTO ESTUDIANTES VALUES('2-0125-0695','ISAAC RODRIGUEZ RODRIGUEZ','22','POAS','INGENIERIA HIDROELECTRICA');

INSERT INTO ESTUDIANTES VALUES('2-0742-0132','KEVIN RODRIGUEZ GONZALES','18','GRECIA, TACARES','INGENIERIA EN SISTEMAS');

INSERT INTO ESTUDIANTES VALUES('1-0253-0152','JOSUE RODRIGURZ ARCE','16','SAN JOSE','ADMINISTRACION DE EMPRESAS');

INSERT INTO ESTUDIANTES VALUES('3-0558-0159','STEVEN CORRALES ALFARO','17','HEREDIA','INGENIERIA QUIMICA');

INSERT INTO ESTUDIANTES VALUES('1-0555-0555','KEYLOR GOMEZ RODRIGUEZ','19','SAN JOSE','ADMINISTRACION DE EMPRESAS');

INSERT INTO ESTUDIANTES VALUES('3-0444-0444','ALEJANDRO MOLINA GOMEZ','15','HEREDIA','INGENIERIA QUIMICA');

SELECT * FROM ESTUDIANTES;

/*INSERTO VALORES A LA TABLA PRESTADOS*/
INSERT INTO PRESTADOS VALUES('1','6',GETDATE(),'2022/06/20','NO');

INSERT INTO PRESTADOS VALUES('2','5',GETDATE(),'2022/07/30','NO');

INSERT INTO PRESTADOS VALUES('3','4',GETDATE(),'2022/06/30','SI');

INSERT INTO PRESTADOS VALUES('4','3',GETDATE(),'2022/06/29','NO');

INSERT INTO PRESTADOS VALUES('5','2',GETDATE(),'2022/07/30','NO');

INSERT INTO PRESTADOS VALUES('6','1',GETDATE(),'2022/06/30','SI');

SELECT * FROM PRESTADOS;


/*Scaffold-DbContext "server=localhost;Database=BIBLIOTECA;Integrated Security = true" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Data*/



/*
Hecho desde c#

CREATE TABLE SEGURIDAD
(
	ID_SEGURIDAD INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	USUARIO VARCHAR(50) NOT NULL,
	NOMBRE_USUARIO VARCHAR(100) NOT NULL,
	CONTRASENA VARCHAR(200) NOT NULL,
	ROL VARCHAR(15) NOT NULL
);
*/


